apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
data:
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  APP_MESSAGE: "Task Manager rodando no Kubernetes"


